apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-products
  name: spring-boot-products
  namespace: default
spec:
  clusterIP: 10.110.61.117
  clusterIPs:
  - 10.110.61.117
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-products
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
