# This is a basic workflow to help you get started with Actions

name: CI-CD workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
            - 'CICD-Demo/**'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Run-Unit-Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Run tests with Gradle
        run: cd CICD-Demo && chmod +x gradlew && ./gradlew test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: my-artifact-name
          path: .

  build-push-docker:
    needs: Run-Unit-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Run Gradle Assemble
        run: cd CICD-Demo && chmod +x gradlew && ./gradlew assemble

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Configure AWS Credentials for ECR access - 
      # Changed from Docker Hub to AWS ECR for image storage and deployment
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

 # Changed from Docker Hub to AWS ECR for image storage and deployment
      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./CICD-Demo
      #     file: ./CICD-Demo/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/springboot-products:latest

      - name: AWS ECR
        uses: kciter/aws-ecr-action@v5
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: singhmagh
          region: us-east-1
          tags: latest
          dockerfile: ./CICD-Demo/Dockerfile
          path: ./CICD-Demo
    
  Deploy-EKS:
    needs: build-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name my-first-cluster --region us-east-1

      - name: Current Context
        run: kubectl config current-context

      - name: Deploy Service
        run: cd CICD-Demo/K8s && kubectl apply -f service.yaml

      - name: Deploy Application
        run: cd CICD-Demo/K8s && kubectl apply -f deployment.yaml

      - name: Verify Pods
        run: kubectl get pods

